# Generated by Django 4.0.4 on 2022-05-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSheets',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('price_dollar', models.FloatField()),
                ('price_ruble', models.FloatField()),
            ],
        ),
    ]
